# fly.toml app configuration file generated for pagesapp on 2023-07-19T17:20:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pagesapp"
primary_region = "dfw"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
